name: Recent Activity

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  push:
    branches:
    - master

jobs:
  build:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_EMAIL: "ljh1553488six@139.com"
